### ISSUE TITLE
Error in get_inception_features

### ISSUE THREAD

**Issue by joseabraham** [rikenmehta03/imsearch#1]
Hi, I had a few issues to get it to run in my computer specially with the encode decode functions with the shape, now I am getting the following error:

Traceback (most recent call last):
  File "/Users/pepe_garcia/opt/anaconda3/lib/python3.7/site-packages/imsearch/feature_extractor/extractor.py", line 93, in <module>
    main()
  File "/Users/pepe_garcia/opt/anaconda3/lib/python3.7/site-packages/imsearch/feature_extractor/extractor.py", line 65, in main
    all_features['secondary'] = get_inception_features(img.copy())
  File "/Users/pepe_garcia/opt/anaconda3/lib/python3.7/site-packages/imsearch/feature_extractor/extractor.py", line 38, in get_inception_features
    x = inception_model.predict(x)
  File "/Users/pepe_garcia/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/Users/pepe_garcia/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/Users/pepe_garcia/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))

ValueError: Error when checking input: expected input_1 to have shape (None, None, 3) but got array with shape (974, 1390, 4)

What could be the issue ?

**Comment by rikenmehta03** [comment]
Can you give me some more details about what are you trying to do? Maybe some code snippet or other details about the system.

**Comment by joseabraham** [comment]
Hi, thanks for the reply, yes I am trying to run it locally

I get it to run but then when I add a PNG image with:
# Add single image to the index
index.addImage(all_images[0]) 

I get an error in this function saying that it can not reshape it:

def decode_image(_q, dtype=np.uint8):
    if sys.version_info.major == 3:
        img = bytes(_q['image'], encoding="utf-8")

    img = np.frombuffer(base64.decodestring(img), dtype=dtype)
    img = img.reshape(_q['shape'])
    return img

I was able to get it working by forcing the dtype to np.float32
def decode_image(_q):
    if sys.version_info.major == 3:
        img = bytes(_q['image'], encoding="utf-8")
    img = np.frombuffer(base64.decodebytes(img), dtype=np.float32)
    img = img.reshape(_q['shape'])
    print('img decode', img)
    return img

But then I run into the error above.

I think I might have an error while encoding and decoding the image and then reshaping it 
The last error happens in this function:

def get_inception_features(x):
    x = preprocess_input(x)
    x = inception_model.predict(np.expand_dims(x, axis=0))
    return base64.b64encode(x[0]).decode("utf-8")

**Comment by rikenmehta03** [comment]
I have pushed the changes that fixes this issue. Thanks for pointing this out.
